"""empty message

Revision ID: 441cb6b37485
Revises: 4ac4f426c31c
Create Date: 2024-01-04 00:08:27.086663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441cb6b37485'
down_revision = '4ac4f426c31c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reps', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('sets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rest', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_column('rest')
        batch_op.drop_column('sets')
        batch_op.drop_column('reps')

    # ### end Alembic commands ###
